=== CONFTEC/PhpDatabaseAnalyzer/libs/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="phpDatabaseAnalyzer">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="outputType" minOccurs="1" maxOccurs="1"></xsd:element>
				<xsd:element name="loggingMode" minOccurs="1" maxOccurs="1"></xsd:element>
				<xsd:element name="databaseTestSuite" minOccurs="1" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="connection" minOccurs="1" maxOccurs="1">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="host" minOccurs="1" maxOccurs="1" />
										<xsd:element name="port" minOccurs="1" maxOccurs="1" />
										<xsd:element name="username" minOccurs="1" maxOccurs="1" />
										<xsd:element name="password" minOccurs="1" maxOccurs="1" />
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="databaseEngine" type="xsd:string" use="required" />
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== CONFTEC/PhpDatabaseAnalyzer/config/example_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<phpDatabaseAnalyzer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../libs/config.xsd">
	<outputType>XML</outputType>
	<loggingMode>full</loggingMode>
	<databaseTestSuite databaseEngine="MySQL">
		<connection>
			<host>localhost</host>
			<port>3306</port>
			<socket></socket>
			<username>root</username>
			<password></password>
			<database>Test</database>
		</connection>
	</databaseTestSuite>
</phpDatabaseAnalyzer>

=== CONFTEC/PhpDatabaseAnalyzer/phpunit/dataProvider/Config/configWithTwoDatabaseTestSuites.xml
<?xml version="1.0" encoding="UTF-8"?>
<phpDatabaseAnalyzer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../libs/config.xsd">
	<outputType>XML</outputType>
	<databaseTestSuite databaseEngine="MySQL">
		<connection>
			<host>localhost</host>
			<port>3306</port>
			<username>root</username>
			<password>9sasjka7a</password>
			<database>testDB1</database>
		</connection>
	</databaseTestSuite>
	<databaseTestSuite databaseEngine="MySQL">
		<connection>
			<host>conftec-testdb01</host>
			<port>3306</port>
			<username>admin</username>
			<password>2kkwsk27</password>
			<database>testDB2</database>
		</connection>
	</databaseTestSuite>
</phpDatabaseAnalyzer>

=== CONFTEC/PhpDatabaseAnalyzer/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<phpDatabaseAnalyzer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../libs/config.xsd">
	<outputType></outputType>
	<databaseTestSuite databaseEngine="MySQL">
		<connection>
			<host>localhost</host>
			<port>3306</port>
			<username>root</username>
			<password></password>
		</connection>
	</databaseTestSuite>
</phpDatabaseAnalyzer>
